const assert=require('node:assert/strict');
const {create,collide,step,driftTier,LENGTH,LAPS}=require('./engine.js');
let state=create();
step(state,{},.05);assert.equal(state.z,0,'Stopped kart must not move.');
for(let i=0;i<100;i++)step(state,{ArrowUp:true},.05);
assert(state.speed>100&&state.z>0,'Acceleration must move the kart.');
assert.deepEqual([driftTier(.64),driftTier(.65),driftTier(1.3),driftTier(2.1)],[0,1,2,3],'Drift charge must have three exact tiers.');
state=create();state.rivals=[];state.z=3800;state.speed=200;
for(let i=0;i<48;i++)step(state,{ArrowUp:true,ArrowRight:true,Shift:true},1/60);
assert(state.drift>.65,'Corner drift must charge.');
step(state,{ArrowUp:true},1/60);assert(state.turbo>0,'Releasing a charged drift must trigger turbo.');
state.turbo=0;state.boost=50;step(state,{' ':true},.05);assert(state.turbo>0&&state.boost<21,'Boost must spend charge.');
state=create();state.z=1000;state.x=0;state.vx=.35;state.speed=220;state.rivals[0].z=1150;state.rivals[0].x=.1;state.rivals[0].vx=0;state.rivals[0].speed=150;
const beforePlayerSpeed=state.speed,beforeRivalSpeed=state.rivals[0].speed,beforeRelativeX=state.vx-state.rivals[0].vx;collide(state,state.rivals[0]);assert(state.bump>0&&state.rivals[0].bump>0,'Both karts must react to impact.');assert(state.speed<beforePlayerSpeed&&state.rivals[0].speed>beforeRivalSpeed,'Longitudinal momentum must transfer to the struck kart.');assert(beforeRelativeX*(state.vx-state.rivals[0].vx)<0,'Lateral relative velocity must reverse after impact.');assert(Math.hypot((state.x-state.rivals[0].x)*520,state.z-state.rivals[0].z)>210,'Penetration correction must separate bodies.');
assert(state.omega!==0&&state.rivals[0].omega!==0,'Off-center impact must rotate both karts.');
state=create();state.z=5000;state.rivals[0].z=7000;const aiStart=state.rivals[0].x;for(let i=0;i<30;i++)step(state,{},.05);assert(Math.abs(state.rivals[0].x-aiStart)>.01,'AI must steer toward a racing line.');
state=create();
for(let i=0;i<6000&&!state.done;i++)step(state,{ArrowUp:true,ArrowLeft:state.x>.25,ArrowRight:state.x<-.25},.05);
assert(state.done&&state.z>=LENGTH*LAPS,'Race must finish after three laps.');
const finished=state.z;step(state,{ArrowUp:true},.05);assert.equal(state.z,finished,'Finished race must stay stopped.');
console.log('PASS: free-flow laps, 3-tier drift, racing-line AI, rotational collision, camera-ready state, three-lap finish');
